### ISSUE TITLE
Error message when changing the instantiation method $router->dispatch gives error

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#29]
As title says im gettin errors 

i used your sample code and i get the following error

Fatal error: Uncaught MiladRahimi\PhpRouter\Exceptions\RouteNotFoundException in /var/www/html/vendor/miladrahimi/phprouter/src/Dispatching/Matcher.php:50 Stack trace: #0 /var/www/html/vendor/miladrahimi/phprouter/src/Router.php(145): MiladRahimi\PhpRouter\Dispatching\Matcher->find(Object(Laminas\Diactoros\ServerRequest), Array) #1 /var/www/html/Storage/configs/web.php(12): MiladRahimi\PhpRouter\Router->dispatch() #2 /var/www/html/Storage/configs/init.php(11): require_once('/var/www/html/S...') #3 /var/www/html/public_html/index.php(4): require_once('/var/www/html/S...') #4 {main} thrown in /var/www/html/vendor/miladrahimi/phprouter/src/Dispatching/Matcher.php on line 50

i am using this to see if it works 

use MiladRahimi\PhpRouter\Router;

$router = Router::create();

$router->get('/', function () {
    return 'This is homepage!';
});

$router->dispatch();

**Comment by itzzpadre** [comment]
Scrap that its working  sorry for wasting any time
